#!/bin/bash
#SBATCH --time=00:20:00  # time allocation, HH:MM:SS
#SBATCH --nodes=1
#SBATCH --partition=single
#SBATCH --job-name=ufm  # job name for the allocation
#SBATCH --output=logs/%x-%j.out

# Run our UFM setup
source ./setup.sh

# Spin one agent
sweep_id=$1
nrun=$2
for ((i=1; i<=$nrun; i++))
do
	wandb agent --count 1 $sweep_id
done
