#!/bin/bash
#SBATCH --time=00:10:00  # time allocation, HH:MM:SS
#SBATCH --nodes=1
#SBATCH --partition=single
#SBATCH --mem=128  # memory per node; default is megabytes; Nvidia A100 has 80G; can use G for gigs etc
#SBATCH --job-name=ufm_test  # job name for the allocation
#SBATCH --output=logs/%x-%j.out

# Run our UFM setup
source ./setup.sh

# python3 main.py
